# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Paulina Lei Reviews
email: paulina.y.lei@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is site where I review things at my discretion.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://paulinalei.github.io" # the base hostname & protocol for your site
github_username:  paulinalei

# Build settings
markdown: kramdown
